#!/bin/bash

BRANCH=gh-pages

make copy
git checkout $BRANCH

DIST=./dist/
if [ -d "$DIST" ]; then
    rsync -av $DIST* .
    rm -rf $DIST
fi

git add -A
git reset publish
git commit -m "new version" && git push origin $BRANCH
git checkout -
